---
title: Choses et autres
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Erick Girard
url: http://erickgirard.com
avatar_url: "//erickgirard.com/img/avatar.png"
github_user: erickgirard
github_repo_url: https://github.com/erickgirard/erickgirard.github.io/
twitter_user: erickgirard
linkedin_user: erickgirard
google_analytics_tracking_id: UA-10726698-3
markdown: rdiscount
pygments: true
permalink: "/archive/:year/:month/:day/:title/"
rdiscount:
  extensions:
  - smart
paginate: 5
paginate_path: page/:num
category_dir: categories
prose:
  siteurl: http://erickgirard.com
  media: assets/img
